# fly.toml app configuration file generated for redis-rating-ui on 2023-12-24T18:41:24+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "redis-rating-ui"
primary_region = "waw"

[build]
  image = "flyio/redis:6.2.6"

[[mounts]]
  source = "redis_rating_ui"
  destination = "/data"
  auto_extend_size_threshold = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[[metrics]]
  port = 9091
  path = "/metrics"
